export interface Template {
  id: string
  name: string
  description: string
  language: string
  framework?: string
  price: number
  icon: string
  features: string[]
  useCase: string
  preview: string
  downloadUrl?: string
  s3Key?: string
}

export const templates: Template[] = [
  {
    id: '01-react-typescript-dashboard',
    name: 'React TypeScript Dashboard',
    description: 'Modern analytics dashboard with real-time data visualization, state management, and responsive design',
    language: 'React',
    framework: 'React 18 + TypeScript + Tailwind CSS',
    price: 29,
    icon: '📊',
    features: [
      'Real-time charts with Recharts',
      'Dark mode support',
      'Redux Toolkit state management',
      'Form validation',
      'API integration ready',
    ],
    useCase: 'Perfect for SaaS dashboards, admin portals, and analytics platforms',
    preview: 'react-dashboard-preview',
    s3Key: '01-react-typescript-dashboard.zip',
    downloadUrl: 'https://code-craft-templates-2024.s3.amazonaws.com/01-react-typescript-dashboard.zip?AWSAccessKeyId=AKIAYGXBGTVG2X6L75MB&Signature=m%2Fa%2Fy9JfpYDbPMBSUaQNwhKzSq0%3D&Expires=1774451380',
  },
  {
    id: '02-vue3-ecommerce',
    name: 'Vue 3 E-Commerce',
    description: 'Full-featured e-commerce storefront with product catalog, shopping cart, and checkout flow',
    language: 'Vue',
    framework: 'Vue 3 + Composition API + Tailwind CSS',
    price: 39,
    icon: '🛒',
    features: [
      'Product listing and filtering',
      'Shopping cart system',
      'Checkout flow',
      'Responsive design',
      'Payment integration ready',
    ],
    useCase: 'Online stores, product marketplaces, retail e-commerce platforms',
    preview: 'vue-ecommerce-preview',
    s3Key: '02-vue3-ecommerce.zip',
    downloadUrl: 'https://code-craft-templates-2024.s3.amazonaws.com/02-vue3-ecommerce.zip?AWSAccessKeyId=AKIAYGXBGTVG2X6L75MB&Signature=mtFbrGnJVWGqF8ccWKqBArhQMFY%3D&Expires=1774451380',
  },
  {
    id: '03-python-fastapi-backend',
    name: 'Python FastAPI Backend',
    description: 'High-performance REST API with async operations, database ORM, and automatic documentation',
    language: 'Python',
    framework: 'FastAPI + SQLAlchemy + PostgreSQL',
    price: 34,
    icon: '🐍',
    features: [
      'Async operations with FastAPI',
      'SQLAlchemy ORM',
      'JWT authentication',
      'Database migrations with Alembic',
      'Swagger API documentation',
    ],
    useCase: 'Backend APIs, microservices, RESTful services, production APIs',
    preview: 'fastapi-backend-preview',
    s3Key: '03-python-fastapi-backend.zip',
    downloadUrl: 'https://code-craft-templates-2024.s3.amazonaws.com/03-python-fastapi-backend.zip?AWSAccessKeyId=AKIAYGXBGTVG2X6L75MB&Signature=eFP%2FH8gsSLdDaSzB6zoQBnFekP8%3D&Expires=1774451380',
  },
  {
    id: '04-nodejs-express-api',
    name: 'Node.js Express API',
    description: 'Feature-rich REST API framework with authentication, validation, and comprehensive error handling',
    language: 'Node.js',
    framework: 'Express.js + TypeScript + MongoDB/PostgreSQL',
    price: 34,
    icon: '⚙️',
    features: [
      'Authentication & authorization',
      'Request validation with Joi',
      'Error handling',
      'Winston logging',
      'Rate limiting',
    ],
    useCase: 'RESTful APIs, backend services, microservices, production applications',
    preview: 'nodejs-api-preview',
    s3Key: '04-nodejs-express-api.zip',
    downloadUrl: 'https://code-craft-templates-2024.s3.amazonaws.com/04-nodejs-express-api.zip?AWSAccessKeyId=AKIAYGXBGTVG2X6L75MB&Signature=Bemd9W%2FMLdBYWqnBo7j2ei%2FRIaw%3D&Expires=1774451380',
  },
  {
    id: '05-typescript-utility-library',
    name: 'TypeScript Utility Library',
    description: 'Production utility library with 40+ helper functions, zero dependencies, and full type safety',
    language: 'TypeScript',
    framework: 'TypeScript + Jest + Rollup',
    price: 24,
    icon: '📦',
    features: [
      '40+ utility functions',
      'Zero external dependencies',
      'Tree-shakeable ESM modules',
      'Full TypeScript support',
      '95%+ test coverage',
    ],
    useCase: 'Reusable libraries, shared utilities, JavaScript/TypeScript projects',
    preview: 'ts-library-preview',
    s3Key: '05-typescript-utility-library.zip',
    downloadUrl: 'https://code-craft-templates-2024.s3.amazonaws.com/05-typescript-utility-library.zip?AWSAccessKeyId=AKIAYGXBGTVG2X6L75MB&Signature=4sxf7iGOw%2FeHgLiT4xEKjOGp7qE%3D&Expires=1774451380',
  },
  {
    id: '06-nextjs-fullstack',
    name: 'Next.js Full-Stack',
    description: 'Complete full-stack SaaS application with server components, API routes, and authentication',
    language: 'React',
    framework: 'Next.js 14 + TypeScript + Prisma',
    price: 49,
    icon: '🚀',
    features: [
      'Server components & API routes',
      'NextAuth.js authentication',
      'Prisma ORM',
      'Real-time database ready',
      'SEO optimized',
    ],
    useCase: 'SaaS applications, full-stack web apps, subscription services',
    preview: 'nextjs-fullstack-preview',
    s3Key: '06-nextjs-fullstack.zip',
    downloadUrl: 'https://code-craft-templates-2024.s3.amazonaws.com/06-nextjs-fullstack.zip?AWSAccessKeyId=AKIAYGXBGTVG2X6L75MB&Signature=wCZ2a5lIV8F7sqwqc5fI7pn%2BXjQ%3D&Expires=1774451380',
  },
  {
    id: '07-nestjs-backend',
    name: 'NestJS Enterprise Backend',
    description: 'Enterprise-grade backend framework with advanced patterns, GraphQL, and microservices support',
    language: 'Node.js',
    framework: 'NestJS + TypeORM + GraphQL',
    price: 44,
    icon: '🏢',
    features: [
      'GraphQL support',
      'CQRS pattern',
      'WebSockets support',
      'Redis caching',
      'Event-driven architecture',
    ],
    useCase: 'Enterprise backends, scalable APIs, complex microservices',
    preview: 'nestjs-backend-preview',
    s3Key: '07-nestjs-backend.zip',
    downloadUrl: 'https://code-craft-templates-2024.s3.amazonaws.com/07-nestjs-backend.zip?AWSAccessKeyId=AKIAYGXBGTVG2X6L75MB&Signature=kSw6cfvm16zCOXyFDZHQ9qSzUtk%3D&Expires=1774451380',
  },
  {
    id: '08-django-rest-backend',
    name: 'Django REST Framework',
    description: 'Powerful Python web API framework with admin interface, permissions, and async tasks',
    language: 'Python',
    framework: 'Django 4.2 + DRF + PostgreSQL',
    price: 39,
    icon: '🟢',
    features: [
      'Django admin interface',
      'Permission system',
      'Celery async tasks',
      'Redis caching',
      'API versioning',
    ],
    useCase: 'Django APIs, Python web services, enterprise backends',
    preview: 'django-rest-preview',
    s3Key: '08-django-rest-backend.zip',
    downloadUrl: 'https://code-craft-templates-2024.s3.amazonaws.com/08-django-rest-backend.zip?AWSAccessKeyId=AKIAYGXBGTVG2X6L75MB&Signature=KPphAWnDBjd69tTW5ZFw3bOEtps%3D&Expires=1774451380',
  },
  {
    id: '09-realtime-chat-app',
    name: 'Real-Time Chat Application',
    description: 'Modern messaging platform with real-time updates, user presence, and file sharing',
    language: 'Full-Stack',
    framework: 'React + Node.js/Express + Socket.io',
    price: 54,
    icon: '💬',
    features: [
      'WebSocket messaging with Socket.io',
      'User presence detection',
      'File sharing support',
      'Message reactions',
      'Read receipts',
    ],
    useCase: 'Chat applications, messaging platforms, real-time collaboration',
    preview: 'chat-app-preview',
    s3Key: '09-realtime-chat-app.zip',
    downloadUrl: 'https://code-craft-templates-2024.s3.amazonaws.com/09-realtime-chat-app.zip?AWSAccessKeyId=AKIAYGXBGTVG2X6L75MB&Signature=7KF2S48HMXuu%2BXVRjk8RakQoJHQ%3D&Expires=1774451380',
  },
  {
    id: '10-ai-chatbot-boilerplate',
    name: 'AI Chatbot Integration Boilerplate',
    description: 'Production AI chatbot with conversation memory, knowledge base search, and streaming responses',
    language: 'Full-Stack',
    framework: 'Node.js + React + OpenAI/Claude + LangChain',
    price: 59,
    icon: '🤖',
    features: [
      'Multi-AI support (OpenAI/Claude)',
      'Streaming response handling',
      'Vector search with Pinecone',
      'Conversation memory',
      'Usage tracking & analytics',
    ],
    useCase: 'AI chatbots, conversational AI, knowledge base systems',
    preview: 'ai-chatbot-preview',
    s3Key: '10-ai-chatbot-boilerplate.zip',
    downloadUrl: 'https://code-craft-templates-2024.s3.amazonaws.com/10-ai-chatbot-boilerplate.zip?AWSAccessKeyId=AKIAYGXBGTVG2X6L75MB&Signature=gAck5tedOpW8ZSxz8WK8bBklRw0%3D&Expires=1774451380',
  },
]
